name: Tests
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Setup
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        export SNIFFS_DIR=/tmp/sniffs
        git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
        git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
    - name: PHP Syntax
      run: find . \( -name '*.php' \) -exec php -lf {} \;
    - name: PHP Compatibility 7.0+
      run: |
        export SNIFFS_DIR=/tmp/sniffs
        php phpcs.phar --config-set installed_paths $SNIFFS_DIR/PHPCompatibility
        php phpcs.phar -p -s -v -n . --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.0-
    - name: WordPress Coding Standards
      run: |
        export SNIFFS_DIR=/tmp/sniffs
        php phpcs.phar --config-set installed_paths $SNIFFS_DIR
        php phpcs.phar -p -s -v -n . --standard=WordPress-Core --extensions=php --ignore=index.asset.php
